language: node_js
env:
  global:
    - JPM_FIREFOX_BINARY=$TRAVIS_BUILD_DIR/firefox/firefox
    - DISPLAY=:99.0
addons:
  firefox: "38.0"
before_script:
  - /usr/bin/xvfb :99 -ac -screen 0 1920x1200x24
  - tar xvjf /tmp/firefox-*.tar.bz2 -C $TRAVIS_BUILD_DIR/
  - npm install jpm -g
script:
  - npm test -s
