language: node_js
env:
  global:
    - JPM_FIREFOX_BINARY=$TRAVIS_BUILD_DIR/firefox/firefox
addons:
  firefox: "38.0"
before_script:
	- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - tar xvjf /tmp/firefox-*.tar.bz2 -C $TRAVIS_BUILD_DIR/
  - npm install jpm -g
script:
  - npm test -s
